version: '3'
services:
  postgres:
    image: postgres:13.2
    restart: always
    ports:
      - '5432:5432'
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: stopwatch_tubesoft
    volumes:
      - ./postgresql/data:/var/lib/postgresql/data
  server:
    build:
      context: ./stopwatch_tubesoft_back
      dockerfile: Dockerfile
    ports:
      - '8000:8000'
    depends_on:
      - postgres
  react-app:
    build:
      context: ./stopwatch_tubesoft_front
      dockerfile: Dockerfile
    ports:
      - '3000:3000'
    depends_on:
      - server
